In [1]:
### 이항-로지스틱회귀모형분석
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

b_cancer = load_breast_cancer()
b_cancer     #dictionary{  }형태의 자료

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [2]:
# 독립변수(b_cancer.feature)로 DataFrame 자료형으로 변환
b_cancer_df = pd.DataFrame(b_cancer.data, columns = b_cancer.feature_names)
b_cancer_df['diagnosis']= b_cancer.target  

In [4]:
# diagnosis는 악성이면 1, 양성이면 0의 값이므로 유방암 여부에 대한 이진 분류
b_cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  diagnosis  
0          0.4601                  0.11890          0  
1          0.2750                  0.08902          0  
2          0.3613                  0.08758          0  
3          0.6638                  0.17300          0  
4          0.2364                  0.07678          0  

[5 rows x 31 columns]

In [5]:
print('유방암 진단 데이터셋 크기: ', b_cancer_df.shape)
b_cancer_df.info()

유방암 진단 데이터셋 크기:  (569, 31)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14 

In [6]:
# 정규분포의 표준화(scaler=standardScaler())함수를 scaler함수로 생성
from sklearn.preprocessing import StandardScaler 
scaler= StandardScaler()
b_cancer_s = scaler.fit_transform(b_cancer.data)

# data[0] ~ 첫번째 행
print(b_cancer.data[0]) #첫번째 변수의 원본데이터
print(b_cancer_s[0])    #첫번쨰 변수의 표준화 데이터

[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
 1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
 6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
 1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
 4.601e-01 1.189e-01]
[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633  3.28351467
  2.65287398  2.53247522  2.21751501  2.25574689  2.48973393 -0.56526506
  2.83303087  2.48757756 -0.21400165  1.31686157  0.72402616  0.66081994
  1.14875667  0.90708308  1.88668963 -1.35929347  2.30360062  2.00123749
  1.30768627  2.61666502  2.10952635  2.29607613  2.75062224  1.93701461]


In [7]:
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split

# input=X, target=Y 설정하기 
Y = b_cancer_df['diagnosis'] 
X = b_cancer_s

In [8]:
#훈련용 데이터와 평가용 데이터 분할하기 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)

#로지스틱 회귀 분석: (1) 모델 생성 
LR_b_cancer = LogisticRegression()

In [9]:
#로지스틱 회귀 분석: (2) 모델 훈련 및 모형적합결과
reg=LR_b_cancer.fit(X_train, Y_train)
print(reg.coef_)
print(np.exp(reg.coef_))
print( "R²=", reg.score(X_train, Y_train))

[[-0.25965337 -0.58891309 -0.27527119 -0.35070364 -0.13501664  0.41458176
  -0.67094946 -0.74096029 -0.37987661  0.03289321 -1.35087219  0.14092099
  -0.90852156 -0.98001244  0.25957915  0.92374666 -0.13448413 -0.34937963
   0.16812679  0.91359164 -0.8473647  -0.91043792 -0.73517119 -0.84764528
  -0.56888501  0.17670599 -0.82594672 -1.08228373 -0.48409262 -0.60758107]]
[[0.7713189  0.55493012 0.75936616 0.70419242 0.87370138 1.5137375
  0.51122296 0.47665597 0.6839458  1.03344017 0.25901425 1.15133368
  0.40311977 0.37530643 1.29638439 2.51870948 0.87416675 0.70512539
  1.18308661 2.49326136 0.42854279 0.40234799 0.47942338 0.42842256
  0.56615635 1.19328021 0.4378203  0.33882087 0.61625612 0.54466679]]
R²= 0.9899497487437185


In [11]:
# 독립변수 30개 이름과 회귀계수 값을 매칭시켜 출력(zip - 매칭하여 묶어줌)
# np.exp(reg.coef_[0])
for f, w in zip(b_cancer.feature_names, np.exp(reg.coef_[0])):
  print(f"{f:<25} {w}")

mean radius               0.7713189008832837
mean texture              0.5549301166989513
mean perimeter            0.7593661621310727
mean area                 0.7041924171171208
mean smoothness           0.8737013756295069
mean compactness          1.5137375047102704
mean concavity            0.5112229609715785
mean concave points       0.4766559686025058
mean symmetry             0.6839457981197254
mean fractal dimension    1.0334401741414716
radius error              0.25901425237350206
texture error             1.151333682769685
perimeter error           0.4031197714621173
area error                0.37530642967976663
smoothness error          1.296384385054804
compactness error         2.5187094761825
concavity error           0.8741667490685986
concave points error      0.705125394327473
symmetry error            1.1830866052039541
fractal dimension error   2.493261360734287
worst radius              0.4285427859528612
worst texture             0.4023479875742604
worst perimeter

In [12]:
#로지스틱 회귀 분석: (3) 훈련자료와 평가자료에 대한 예측 수행 -> 예측 결과 Y_predict 구하기 
Y_fit=LR_b_cancer.predict(X_train)
Y_pred = LR_b_cancer.predict(X_test)

In [16]:
#오차 행렬( )
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_train, Y_fit)) 
print(confusion_matrix(Y_test, Y_pred))

[[145   4]
 [  0 249]]
[[ 60   3]
 [  1 107]]


In [18]:
# 정확도, 정밀도, 재현성
from sklearn.metrics import accuracy_score, precision_score, recall_score
acccuracy = accuracy_score(Y_test, Y_pred) 
precision = precision_score(Y_test, Y_pred) 
recall = recall_score(Y_test, Y_pred) 
print('정확도: {0:.3f}, 정밀도: {1:.3f}, 재현율: {2:.3f}'.format(acccuracy,precision,recall))

정확도: 0.977, 정밀도: 0.973, 재현율: 0.991


In [19]:
# 모형평가(분류정확도_보고서) 종합정리
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.97        63
           1       0.97      0.99      0.98       108

    accuracy                           0.98       171
   macro avg       0.98      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171



In [21]:
### 다항-로지스틱회귀모형분석 : iris 
from sklearn.datasets import load_iris
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [22]:
# input=X, target=Y 설정하기 
X = iris.data
Y = iris.target

In [23]:
# iris_df 데이터프레임에 독립변수와 종속변수를 병합(dictionary -> matrix-data)
iris_df= pd.DataFrame(X, columns=iris.feature_names)
iris_df['species']= iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [24]:
# 독립변수의 이름 바꾸기
iris_df = iris_df.rename(
    columns={
        "sepal length (cm)": "sepal_length",
        "sepal width (cm)": "sepal_width",
        "petal length (cm)": "petal_length",
        "petal width (cm)": "petal_width",
    })
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [25]:
y = iris_df['species']
x = iris_df[['sepal_length','sepal_width','petal_length','petal_width']]

In [26]:
#훈련용 데이터와 평가용 데이터 분할하기 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

#로지스틱 회귀 분석: (1) 모델 생성 
LR_iris = LogisticRegression()

In [28]:
#로지스틱 회귀 분석: (2) 모델 훈련 및 모형적합결과
reg=LR_iris.fit(x_train, y_train)
print(iris.feature_names, reg.coef_)
print(iris.feature_names, np.exp(reg.coef_))
print( "R²=", reg.score(x_train, y_train))

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] [[-0.39753126  0.83334148 -2.28937951 -0.97844325]
 [ 0.54384873 -0.28990373 -0.23240047 -0.65814544]
 [-0.14631747 -0.54343775  2.52177998  1.63658869]]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] [[ 0.67197694  2.30099464  0.10132932  0.37589582]
 [ 1.72262403  0.74833561  0.79262864  0.51781076]
 [ 0.8638834   0.58074835 12.45073902  5.13761361]]
R²= 0.9809523809523809


C:\Users\gksxk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [29]:
#로지스틱 회귀 분석: (3) 훈련자료와 평가자료에 대한 예측 수행 -> 예측 결과 Y_predict 구하기 
y_fit=LR_iris.predict(x_train)
y_pred = LR_iris.predict(x_test)

In [32]:
#혼동행렬
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, y_fit)

array([[34,  0,  0],
       [ 0, 30,  2],
       [ 0,  0, 39]], dtype=int64)

In [33]:
confusion_matrix(y_test, y_pred)

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)

In [34]:
# 모형평가(분류정확도_보고서) 종합정리
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

