In [1]:
#한글폰트 파일실행
!python han-font.py
exec(open('han-font.py').read())
import numpy as np
import pandas as pd

credit=pd.read_csv("credit.csv", encoding="CP949")
credit.head()

checking_balance  months_loan_duration credit_history  amount  \
0           < 0 DM                     6       critical    1169   
1       1 - 200 DM                    48           good    5951   
2          unknown                    12       critical    2096   
3           < 0 DM                    42           good    7882   
4           < 0 DM                    24           poor    4870   

  savings_balance employment_duration  percent_of_income  years_at_residence  \
0         unknown           > 7 years                  4                   4   
1        < 100 DM         1 - 4 years                  2                   2   
2        < 100 DM         4 - 7 years                  2                   3   
3        < 100 DM         4 - 7 years                  2                   4   
4        < 100 DM         1 - 4 years                  3                   4   

   age housing  existing_loans_count        job default  
0   67     own                     2    skilled      no  
1   22     own                     1    skilled     yes  
2   49     own                     1  unskilled      no  
3   45   other                     1    skilled      no  
4   53   other                     2    skilled     yes

In [2]:
credit1=pd.get_dummies(credit)
credit1

months_loan_duration  amount  percent_of_income  years_at_residence  age  \
0                       6    1169                  4                   4   67   
1                      48    5951                  2                   2   22   
2                      12    2096                  2                   3   49   
3                      42    7882                  2                   4   45   
4                      24    4870                  3                   4   53   
..                    ...     ...                ...                 ...  ...   
995                    12    1736                  3                   4   31   
996                    30    3857                  4                   4   40   
997                    12     804                  4                   4   38   
998                    45    1845                  4                   4   23   
999                    45    4576                  3                   4   27   

     existing_loans_count  checking_balance_1 - 200 DM  \
0                       2                            0   
1                       1                            1   
2                       1                            0   
3                       1                            0   
4                       2                            0   
..                    ...                          ...   
995                     1                            0   
996                     1                            0   
997                     1                            0   
998                     1                            0   
999                     1                            1   

     checking_balance_< 0 DM  checking_balance_> 200 DM  \
0                          1                          0   
1                          0                          0   
2                          0                          0   
3                          1                          0   
4                          1                          0   
..                       ...                        ...   
995                        0                          0   
996                        1                          0   
997                        0                          0   
998                        1                          0   
999                        0                          0   

     checking_balance_unknown  ...  employment_duration_unemployed  \
0                           0  ...                               0   
1                           0  ...                               0   
2                           1  ...                               0   
3                           0  ...                               0   
4                           0  ...                               0   
..                        ...  ...                             ...   
995                         1  ...                               0   
996                         0  ...                               0   
997                         1  ...                               0   
998                         0  ...                               0   
999                         0  ...                               1   

     housing_other  housing_own  housing_rent  job_management  job_skilled  \
0                0            1             0               0            1   
1                0            1             0               0            1   
2                0            1             0               0            0   
3                1            0             0               0            1   
4                1            0             0               0            1   
..             ...          ...           ...             ...          ...   
995              0            1             0               0            0   
996              0            1             0               1            0   
997              0            1             0               0            1   
998  

In [2]:
print('credit 데이터셋 크기: ', credit.shape)
credit.info()

credit 데이터셋 크기:  (1000, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   checking_balance      1000 non-null   object
 1   months_loan_duration  1000 non-null   int64 
 2   credit_history        1000 non-null   object
 3   amount                1000 non-null   int64 
 4   savings_balance       1000 non-null   object
 5   employment_duration   1000 non-null   object
 6   percent_of_income     1000 non-null   int64 
 7   years_at_residence    1000 non-null   int64 
 8   age                   1000 non-null   int64 
 9   housing               1000 non-null   object
 10  existing_loans_count  1000 non-null   int64 
 11  job                   1000 non-null   object
 12  default               1000 non-null   object
dtypes: int64(6), object(7)
memory usage: 101.7+ KB


In [3]:
# 질적변수를 더미변수로 변환
# 질적변수 -> 더미변수
credit_data1 = pd.get_dummies(credit.loc[:,['checking_balance', 'credit_history', 'savings_balance',
                                            'employment_duration', 'housing', 'job']])
# 양적변수 & target
credit_data2=credit.loc[:, ['months_loan_duration', 'amount', 'percent_of_income',
                            'years_at_residence', 'age', 'existing_loans_count', 'default']]
# 분석에 사용되는 데이터셋
credit_data=credit_data1.join(credit_data2)
credit_data.head()

checking_balance_1 - 200 DM  checking_balance_< 0 DM  \
0                            0                        1   
1                            1                        0   
2                            0                        0   
3                            0                        1   
4                            0                        1   

   checking_balance_> 200 DM  checking_balance_unknown  \
0                          0                         0   
1                          0                         0   
2                          0                         1   
3                          0                         0   
4                          0                         0   

   credit_history_critical  credit_history_good  credit_history_perfect  \
0                        1                    0                       0   
1                        0                    1                       0   
2                        1                    0                       0   
3                        0                    1                       0   
4                        0                    0                       0   

   credit_history_poor  credit_history_very good  \
0                    0                         0   
1                    0                         0   
2                    0                         0   
3                    0                         0   
4                    1                         0   

   savings_balance_100 - 500 DM  ...  job_skilled  job_unemployed  \
0                             0  ...            1               0   
1                             0  ...            1               0   
2                             0  ...            0               0   
3                             0  ...            1               0   
4                             0  ...            1               0   

   job_unskilled  months_loan_duration  amount  percent_of_income  \
0              0                     6    1169                  4   
1              0                    48    5951                  2   
2              1                    12    2096                  2   
3              0                    42    7882                  2   
4              0                    24    4870                  3   

   years_at_residence  age  existing_loans_count  default  
0                   4   67                     2       no  
1                   2   22                     1      yes  
2                   3   49                     1       no  
3                   4   45                     1       no  
4                   4   53                     2      yes  

[5 rows x 33 columns]

In [4]:
# 독립변수(수치형 자료)와 종속변수(target)
# 독립변수 6개 이름과 회귀계수 값을 매칭시켜 출력(zip - 매칭하여 묶어줌)
x_data=credit_data.iloc[:,:-1]
y_data=credit_data["default"]

In [5]:
#훈련용 데이터와 평가용 데이터 분할하기
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.2, random_state = 0)

In [6]:
# x_train과 x_test를 StandardScaler를 이용해 정규화
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_train=pd.DataFrame(x_train, columns=x_data.columns)
x_test=pd.DataFrame(x_test, columns=x_data.columns)
x_train.head()

checking_balance_1 - 200 DM  checking_balance_< 0 DM  \
0                     1.654786                -0.619744   
1                    -0.604308                 1.613569   
2                     1.654786                -0.619744   
3                     1.654786                -0.619744   
4                    -0.604308                -0.619744   

   checking_balance_> 200 DM  checking_balance_unknown  \
0                  -0.260942                 -0.801692   
1                  -0.260942                 -0.801692   
2                  -0.260942                 -0.801692   
3                  -0.260942                 -0.801692   
4                  -0.260942                  1.247361   

   credit_history_critical  credit_history_good  credit_history_perfect  \
0                -0.652706            -1.048684               -0.210681   
1                -0.652706             0.953576               -0.210681   
2                -0.652706             0.953576               -0.210681   
3                -0.652706            -1.048684               -0.210681   
4                 1.532084            -1.048684               -0.210681   

   credit_history_poor  credit_history_very good  \
0             3.229330                 -0.223313   
1            -0.309662                 -0.223313   
2            -0.309662                 -0.223313   
3            -0.309662                  4.478016   
4            -0.309662                 -0.223313   

   savings_balance_100 - 500 DM  ...  job_management  job_skilled  \
0                      3.064247  ...       -0.413888     0.764303   
1                     -0.326344  ...       -0.413888     0.764303   
2                      3.064247  ...        2.416114    -1.308382   
3                      3.064247  ...       -0.413888     0.764303   
4                     -0.326344  ...       -0.413888     0.764303   

   job_unemployed  job_unskilled  months_loan_duration    amount  \
0       -0.155974      -0.498046              1.266142 -0.133708   
1       -0.155974      -0.498046              0.270242 -0.041477   
2       -0.155974      -0.498046              3.257942  1.472742   
3       -0.155974      -0.498046             -0.476683 -0.698405   
4       -0.155974      -0.498046             -1.223608 -0.595925   

   percent_of_income  years_at_residence       age  existing_loans_count  
0           0.903680            0.128451 -0.508707             -0.715967  
1           0.903680           -1.706566 -0.767043             -0.715967  
2           0.903680           -0.789057 -1.025380             -0.715967  
3          -0.896927           -0.789057 -0.939268             -0.715967  
4          -1.797231           -0.789057 -1.025380              1.041007  

[5 rows x 32 columns]

In [38]:
#1. 로지스틱 회귀
#로지스틱 회귀 분석: (1) 모델 생성
from sklearn.linear_model import LogisticRegression
credit_LR = LogisticRegression()

In [39]:
#로지스틱 회귀 분석: (2) 모델 훈련 및 모형적합결과
reg=credit_LR.fit(x_train, y_train)

In [56]:
# 로지스틱 회귀 분류 정확도
print( "score =", reg.score(x_test, y_test))

score = 0.745


In [9]:
# 독립변수 이름과 회귀계수 값을 매칭시켜 출력(zip - 매칭하여 묶어줌)
for f, w in zip(x_train.columns, np.exp(reg.coef_[0])):
  print(f"{f:<25} {w}")

checking_balance_1 - 200 DM 1.1328829490675425
checking_balance_< 0 DM   1.4546733928692097
checking_balance_> 200 DM 0.945867892491095
checking_balance_unknown  0.6510517496957141
credit_history_critical   0.7428025501066803
credit_history_good       1.069377974179603
credit_history_perfect    1.2647386683043877
credit_history_poor       0.9820291420398438
credit_history_very good  1.3279640931625178
savings_balance_100 - 500 DM 1.0833754610850594
savings_balance_500 - 1000 DM 1.017901950127818
savings_balance_< 100 DM  1.1737150915086974
savings_balance_> 1000 DM 0.9204662125994968
savings_balance_unknown   0.7953056507541386
employment_duration_1 - 4 years 1.0669990273564343
employment_duration_4 - 7 years 0.8173605085249412
employment_duration_< 1 year 1.233351512801872
employment_duration_> 7 years 0.9399842030328793
employment_duration_unemployed 0.9742237337567962
housing_other             0.9669048434640265
housing_own               0.9210462652716493
housing_rent              

In [10]:
#로지스틱 회귀 분석: (3) 평가자료에 대한 예측 수행 -> 예측 결과 Y_predict 구하기 
from sklearn.metrics import confusion_matrix, accuracy_score 
from sklearn.metrics import precision_score, recall_score
y_pred = credit_LR.predict(x_test)
print(confusion_matrix(y_test, y_pred))

[[123  19]
 [ 32  26]]


In [11]:
# 정확도, 정밀도, 재현성 -> 정확도 중요
acccuracy = accuracy_score(y_test, y_pred) 
precision = precision_score(y_test, y_pred, pos_label="yes") 
recall = recall_score(y_test, y_pred, pos_label="yes") 
print('정확도: {0:.3f}, 정밀도: {1:.3f}, 재현율: {2:.3f}'.format(acccuracy,precision,recall))
# 모형평가(분류정확도_보고서) 종합정리
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

정확도: 0.745, 정밀도: 0.578, 재현율: 0.448
              precision    recall  f1-score   support

          no       0.79      0.87      0.83       142
         yes       0.58      0.45      0.50        58

    accuracy                           0.74       200
   macro avg       0.69      0.66      0.67       200
weighted avg       0.73      0.74      0.73       200



In [12]:
# svm - 의미있는 양적자료 사용( ) 
# 'months_loan_duration', 'amount', 'percent_of_income', 'age', 'existing_loans_count
numeric_xtrain=x_train.loc[:, ['months_loan_duration', 'amount', 'percent_of_income',
                              'age', 'existing_loans_count']]
numeric_xtest=x_test.loc[:, ['months_loan_duration', 'amount', 'percent_of_income',
                              'age', 'existing_loans_count']]
numeric_xtrain.head()

months_loan_duration    amount  percent_of_income       age  \
0              1.266142 -0.133708           0.903680 -0.508707   
1              0.270242 -0.041477           0.903680 -0.767043   
2              3.257942  1.472742           0.903680 -1.025380   
3             -0.476683 -0.698405          -0.896927 -0.939268   
4             -1.223608 -0.595925          -1.797231 -1.025380   

   existing_loans_count  
0             -0.715967  
1             -0.715967  
2             -0.715967  
3             -0.715967  
4              1.041007

In [13]:
# 2. svm
import pandas as pd
from sklearn.svm import SVC  
from sklearn.metrics import classification_report, confusion_matrix  

In [43]:
# SVM - 분류정확도 분석(선형)
svclassifier = SVC(kernel='linear')  
svclassifier.fit(numeric_xtrain, y_train) 
y_pred = svclassifier.predict(numeric_xtest)  
print(confusion_matrix(y_test, y_pred))  

[[142   0]
 [ 58   0]]


In [44]:
print('score : ',svclassifier.score(numeric_xtest,y_test))

score :  0.71


In [15]:
# 정확도, 정밀도, 재현성 -> 정확도 중요
acccuracy = accuracy_score(y_test, y_pred) 
precision = precision_score(y_test, y_pred, pos_label="yes") 
recall = recall_score(y_test, y_pred, pos_label="yes") 
print('정확도: {0:.3f}, 정밀도: {1:.3f}, 재현율: {2:.3f}'.format(acccuracy,precision,recall))
# 모형평가(분류정확도_보고서) 종합정리
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

정확도: 0.710, 정밀도: 0.000, 재현율: 0.000
              precision    recall  f1-score   support

          no       0.71      1.00      0.83       142
         yes       0.00      0.00      0.00        58

    accuracy                           0.71       200
   macro avg       0.35      0.50      0.42       200
weighted avg       0.50      0.71      0.59       200



C:\Users\gksxk\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\gksxk\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\gksxk\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\gksxk\anaconda3\lib\site-packages\sklearn\metrics\_classification.p

In [45]:
# SVM - 커널함수= 다항식(poly)
svclassifier = SVC(kernel='poly', degree=8)  
svclassifier.fit(numeric_xtrain, y_train) 
y_pred = svclassifier.predict(numeric_xtest)  
print(confusion_matrix(y_test, y_pred)) 

[[131  11]
 [ 49   9]]


In [46]:
print('score : ',svclassifier.score(numeric_xtest,y_test))

score :  0.7


In [17]:
# 정확도, 정밀도, 재현성 -> 정확도 중요
acccuracy = accuracy_score(y_test, y_pred) 
precision = precision_score(y_test, y_pred, pos_label="yes") 
recall = recall_score(y_test, y_pred, pos_label="yes") 
print('정확도: {0:.3f}, 정밀도: {1:.3f}, 재현율: {2:.3f}'.format(acccuracy,precision,recall))
# 모형평가(분류정확도_보고서) 종합정리
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

정확도: 0.700, 정밀도: 0.450, 재현율: 0.155
              precision    recall  f1-score   support

          no       0.73      0.92      0.81       142
         yes       0.45      0.16      0.23        58

    accuracy                           0.70       200
   macro avg       0.59      0.54      0.52       200
weighted avg       0.65      0.70      0.64       200



In [47]:
# SVM - 커널함수= 가우시안(정규분포함수)
svclassifier = SVC(kernel='rbf')  
svclassifier.fit(numeric_xtrain, y_train) 
y_pred = svclassifier.predict(numeric_xtest)  
print(confusion_matrix(y_test, y_pred))

[[137   5]
 [ 51   7]]


In [48]:
print('score : ',svclassifier.score(numeric_xtest,y_test))

score :  0.72


In [19]:
# 정확도, 정밀도, 재현성 -> 정확도 중요
acccuracy = accuracy_score(y_test, y_pred) 
precision = precision_score(y_test, y_pred, pos_label="yes") 
recall = recall_score(y_test, y_pred, pos_label="yes") 
print('정확도: {0:.3f}, 정밀도: {1:.3f}, 재현율: {2:.3f}'.format(acccuracy,precision,recall))
# 모형평가(분류정확도_보고서) 종합정리
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

정확도: 0.720, 정밀도: 0.583, 재현율: 0.121
              precision    recall  f1-score   support

          no       0.73      0.96      0.83       142
         yes       0.58      0.12      0.20        58

    accuracy                           0.72       200
   macro avg       0.66      0.54      0.52       200
weighted avg       0.69      0.72      0.65       200



In [49]:
# SVM - 커널함수= sigmoid
svclassifier = SVC(kernel='sigmoid')  
svclassifier.fit(numeric_xtrain, y_train) 
y_pred = svclassifier.predict(numeric_xtest)  
print(confusion_matrix(y_test, y_pred)) 

[[115  27]
 [ 42  16]]


In [50]:
print('score : ',svclassifier.score(numeric_xtest,y_test))

score :  0.655


In [21]:
# 정확도, 정밀도, 재현성 -> 정확도 중요
acccuracy = accuracy_score(y_test, y_pred) 
precision = precision_score(y_test, y_pred, pos_label="yes") 
recall = recall_score(y_test, y_pred, pos_label="yes") 
print('정확도: {0:.3f}, 정밀도: {1:.3f}, 재현율: {2:.3f}'.format(acccuracy,precision,recall))
# 모형평가(분류정확도_보고서) 종합정리
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

정확도: 0.655, 정밀도: 0.372, 재현율: 0.276
              precision    recall  f1-score   support

          no       0.73      0.81      0.77       142
         yes       0.37      0.28      0.32        58

    accuracy                           0.66       200
   macro avg       0.55      0.54      0.54       200
weighted avg       0.63      0.66      0.64       200



In [27]:
# 3. 판별분석(DA)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [28]:
# 전체 자료에 대한 판별분석
lda = LinearDiscriminantAnalysis()
lda.fit(x_train, y_train)

LinearDiscriminantAnalysis()

In [51]:
# 모형예측(분류) 
y_pred= lda.predict(x_test)
confusion_matrix(y_test, y_pred)

array([[124,  18],
       [ 34,  24]], dtype=int64)

In [53]:
print('score : ',lda.score(x_test,y_test))

score :  0.74


In [30]:
# 정확도, 정밀도, 재현성 -> 정확도 중요
acccuracy = accuracy_score(y_test, y_pred) 
precision = precision_score(y_test, y_pred, pos_label="yes") 
recall = recall_score(y_test, y_pred, pos_label="yes") 
print('정확도: {0:.3f}, 정밀도: {1:.3f}, 재현율: {2:.3f}'.format(acccuracy,precision,recall))
# 모형평가(분류정확도_보고서) 종합정리
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

정확도: 0.740, 정밀도: 0.571, 재현율: 0.414
              precision    recall  f1-score   support

          no       0.78      0.87      0.83       142
         yes       0.57      0.41      0.48        58

    accuracy                           0.74       200
   macro avg       0.68      0.64      0.65       200
weighted avg       0.72      0.74      0.73       200



In [31]:
# 4. 신경망
# 다층인공신경망(MLP) 분류 알고리즘을 sklearn의 neural_network에서 로드
from sklearn.neural_network import MLPClassifier
# MLP 알고리즘의 히든레이어를 3계층(10,10,10)으로 할당
mlp = MLPClassifier(hidden_layer_sizes=(10,10,10))

In [32]:
# 위에서 분류한 X_train과 y_train을 MLP를 이용해 학습
mlp.fit(x_train, y_train)

C:\Users\gksxk\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(10, 10, 10))

In [54]:
y_pred = mlp.predict(x_test)
print(confusion_matrix(y_test, y_pred))

[[109  33]
 [ 30  28]]


In [55]:
print('score : ',mlp.score(x_test,y_test))

score :  0.685


In [37]:
# 정확도, 정밀도, 재현성 -> 정확도 중요
acccuracy = accuracy_score(y_test, y_pred) 
precision = precision_score(y_test, y_pred, pos_label="yes") 
recall = recall_score(y_test, y_pred, pos_label="yes") 
print('정확도: {0:.3f}, 정밀도: {1:.3f}, 재현율: {2:.3f}'.format(acccuracy,precision,recall))
# classification_report를 이용해 정확률, 재현율 등을 확인  
print(classification_report(y_test, y_pred))

정확도: 0.685, 정밀도: 0.459, 재현율: 0.483
              precision    recall  f1-score   support

          no       0.78      0.77      0.78       142
         yes       0.46      0.48      0.47        58

    accuracy                           0.69       200
   macro avg       0.62      0.63      0.62       200
weighted avg       0.69      0.69      0.69       200

